name: Python CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  file_organiser:
    uses: ./.github/actions/tests.yml
    with:
      project-path: Beginner/file_organiser
