name: Reusable Python CI

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.project-path }}/requirements.txt
        pip install ruff black mypy pytest pytest-cov

    - name: Lint with ruff
      continue-on-error: true
      run: ruff check ${{ inputs.project-path }}/src ${{ inputs.project-path }}/tests

    - name: Format with black
      run: black --check ${{ inputs.project-path }}/src ${{ inputs.project-path }}/tests

    - name: Typecheck with mypy
      run: mypy ${{ inputs.project-path }}/src

    - name: Test with pytest and generate coverage summary
      run: |
        pytest --cov=${{ inputs.project-path }}/src --cov-report=term-missing ${{ inputs.project-path }}/tests > coverage_summary.md

    - name: Display coverage summary in job summary
      run: |
        echo "## Code Coverage Summary for $(echo ${{ inputs.project-path }} | cut -d '/' -f 2)" >> $GITHUB_STEP_SUMMARY
        echoinputs.project-path })" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat coverage_summary.md >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
